# Generated by Django 5.0.6 on 2024-06-26 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_amount', models.IntegerField()),
                ('expense_name', models.CharField(max_length=30)),
                ('expense_category', models.CharField(choices=[('PER', 'PERSONAL'), ('MED', 'MEDICAL'), ('OFF', 'OFFICE')], max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
