# Generated by Django 5.0.6 on 2024-06-26 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_exp_mgmt', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transaction',
            new_name='Expense',
        ),
    ]
