# Generated by Django 5.0.6 on 2024-06-28 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_exp_mgmt', '0002_rename_transaction_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='expense_category',
            field=models.CharField(choices=[('PER', 'PERSONAL'), ('MED', 'MEDICAL'), ('OFF', 'OFFICE'), ('STN', 'STATIONARY')], max_length=20),
        ),
    ]
