# Generated by Django 5.0.6 on 2024-06-28 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_exp_mgmt', '0003_alter_expense_expense_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategoryChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_category', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_exp_mgmt.expensecategorychoice'),
        ),
    ]
